name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'
          
    - name: Install Flutter Version 3.29.3
      uses: subosito/flutter-action@v2
      with:
          flutter-version: '3.29.3' # Use the required Flutter version


    - name: Install Dependencies
      run: flutter pub get

    - name: Run Our Test
      run: flutter test

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: "3.3.8"
          bundler-cache: true
          working-directory: android

    - name: Deploy to Firebase via Fastlane
      working-directory: android
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution_gingoman
      working-directory: android

