// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSCzAaglSQ8unBCgcklYmIAk5ybiO-lk',
    appId: '1:508583010425:web:015ed5e4404a48999df4a8',
    messagingSenderId: '508583010425',
    projectId: 'com-mdhossam32547-gingoman',
    authDomain: 'com-mdhossam32547-gingoman.firebaseapp.com',
    storageBucket: 'com-mdhossam32547-gingoman.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPsK-Esuml1Fe1RV09evETjtejU7auC8',
    appId: '1:508583010425:android:6a7accb581ff48649df4a8',
    messagingSenderId: '508583010425',
    projectId: 'com-mdhossam32547-gingoman',
    storageBucket: 'com-mdhossam32547-gingoman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxjgbQzrVEmKFtBxX0xfBYGrEwrYS4nQ',
    appId: '1:508583010425:ios:ce3c765ae928104a9df4a8',
    messagingSenderId: '508583010425',
    projectId: 'com-mdhossam32547-gingoman',
    storageBucket: 'com-mdhossam32547-gingoman.firebasestorage.app',
    iosBundleId: 'com.example.gingoMan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARxjgbQzrVEmKFtBxX0xfBYGrEwrYS4nQ',
    appId: '1:508583010425:ios:ce3c765ae928104a9df4a8',
    messagingSenderId: '508583010425',
    projectId: 'com-mdhossam32547-gingoman',
    storageBucket: 'com-mdhossam32547-gingoman.firebasestorage.app',
    iosBundleId: 'com.example.gingoMan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwSCzAaglSQ8unBCgcklYmIAk5ybiO-lk',
    appId: '1:508583010425:web:eced7e5774e024c99df4a8',
    messagingSenderId: '508583010425',
    projectId: 'com-mdhossam32547-gingoman',
    authDomain: 'com-mdhossam32547-gingoman.firebaseapp.com',
    storageBucket: 'com-mdhossam32547-gingoman.firebasestorage.app',
  );
}
